- name: Test Ansible connection
  hosts: debian_vms
  gather_facts: false

  vars:
    # Default 30 Sekunden, kann in Semaphore per Extra Vars überschrieben werden
    ping_interval: "{{ ping_interval | default(30) }}"

  tasks:
    - name: Ping the target machines
      ansible.builtin.ping:

    - name: Pause before next ping
      ansible.builtin.pause:
        seconds: "{{ ping_interval | int }}"
      when: ping_interval | int > 0
