- name: Test Ansible connection
  hosts: debian_vms
  gather_facts: false

  vars:
    # separater Default-Wert, kein rekursiver Bezug
    default_ping_interval: 30

  tasks:
    - name: Ping the target machines
      ansible.builtin.ping:

    - name: Pause before next ping
      ansible.builtin.pause:
        # benutze entweder die Extra-Var ping_interval oder den Default
        seconds: "{{ (ping_interval | default(default_ping_interval)) | int }}"
      when: "(ping_interval | default(default_ping_interval) | int) > 0"
